import type { Metadata } from 'next';
import Footer from '../components/footer';
import Header from '../components/header';
import MoveClouds from '../components/move_clouds';
import ReturnTopButton from '../components/return_top_button';
import { newTegomin, notoSansJP } from '../utils/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[url('/hero_header/hero_header.svg')] bg-cover bg-fixed bg-center min-h-screen  ${notoSansJP.className} ${notoSansJP.variable} ${newTegomin.variable} antialiased`}
      >
       <div className="absolute -z-10"><MoveClouds/></div>
        

        <Header />
        <div className="mt-20 z-20">
          <div>
            <ReturnTopButton />
          </div>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
